In [1]:
import pandas as pd
import numpy as np
import chardet

In [2]:
fh = '/home/samarth/Documents/python codes/Ml basics/Projects/NLP-Bag Of Words/mail.csv'

In [3]:
with open(fh,'rb') as mail_raw:
    coding = chardet.detect(mail_raw.read(100000))
coding

{'encoding': 'Windows-1252', 'confidence': 0.73, 'language': ''}

In [4]:
dataset = pd.read_csv('mail.csv', encoding='Windows-1252')

In [5]:
dataset.drop('S. No.',axis = 'columns',inplace = True)
dataset.head()

Message_body     Label
0                         Rofl. Its true to its name  Non-Spam
1  The guy did some bitching but I acted like i'd...  Non-Spam
2  Pity, * was in mood for that. So...any other s...  Non-Spam
3               Will ü b going to esplanade fr home?  Non-Spam
4  This is the 2nd time we have tried 2 contact u...      Spam

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['Label'] = le.fit_transform(dataset['Label'])

In [7]:
dataset['Label']

0      0
1      0
2      0
3      0
4      1
      ..
952    0
953    0
954    0
955    0
956    0
Name: Label, Length: 957, dtype: int64

In [8]:
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

corpus = []
for i in range(0,957):
    mail = re.sub('[^a-zA-Z]',' ',dataset['Message_body'][i])
    mail = mail.lower()
    mail = mail.split()
    ps = PorterStemmer()
    stpwords = stopwords.words('english')
    stpwords.remove('not')
    mail = [ps.stem(word) for word in mail if word not in set(stpwords)]
    mail = ' '.join(mail)
    corpus.append(mail)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/samarth/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [9]:
corpus

['rofl true name',
 'guy bitch act like interest buy someth els next week gave us free',
 'piti mood suggest',
 'b go esplanad fr home',
 'nd time tri contact u u pound prize claim easi call p per minut bt nation rate',
 'remind get pound free call credit detail great offer pl repli text valid name hous postcod',
 'huh lei',
 'wait til least wednesday see get',
 'ard like dat lor',
 'ok lor soni ericsson salesman ask shuhui say quit gd use consid',
 'get dump heap mom decid come low bore',
 'anyth lor juz us lor',
 'next lt gt hour imma flip shit',
 'sorri call later',
 'meant calcul lt gt unit lt gt school realli expens start practic accent import decid year dental school nmde exam',
 'ye u text pshew miss much',
 'yeh indian nice tho kane bit shud go drink sometim soon mite hav go da work laugh soon love pete x x',
 'well keep mind got enough ga one round trip bar sudden influx cash',
 'hahaha use brain dear',
 'safe trip nigeria wish happi soon compani share moment',
 'wen get spiri

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2360)
x = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:,-1].values
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.8,random_state=0)

In [17]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [18]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_pred,y_test)
print(cm)

[[151  11]
 [ 11  19]]


In [20]:
accuracy = accuracy_score(y_pred, y_test)
print(accuracy)

0.8854166666666666


In [ ]:
mail_inp = str(input('Enter your mail '))

In [244]:
mail_inp = re.sub('[^a-zA-Z]',' ',mail_inp)
mail_inp = mail_inp.lower()
mail_inp = mail_inp.split()
mail_inp = [ps.stem(inp) for inp in mail_inp if inp not in set(stpwords)]
mail_inp = ' '.join(mail_inp)
mail_inp = [mail_inp]
print(mail_inp)

['privat account statement show un redeem point call identifi code expir']


In [245]:
mail_inp = cv.transform(mail_inp).toarray()
print(mail_inp)

[[0 0 0 ... 0 0 0]]


In [246]:
y_pred = classifier.predict(mail_inp)
print(y_pred)

[1]
